### ISSUE TITLE
Issues with selection

### ISSUE THREAD

**Issue by cajunitalian** [vtagion/Scripts#4]
The script is actually pulling all my datastores instead of just the ones that are presented to all hosts.

Then when I select a Datastore that actually IS shared across hosts, I get this error:

```
Continuing with Shared Datastore: V3_ESX_ISO_LUN-DevID-005F
New-PSDrive : Cannot bind parameter 'Datastore' to the target. Exception setting "Datastore": "Invalid location type. Location accepts
only VIDatastore objects."
At C:\Users\mdadmin\Desktop\ProductLockerAutomation.ps1:54 char:23
+ New-PSDrive -Location $Datastore -Name PL -PSProvider VimDatastore -Root '\' | o ...
+                       ~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PSDrive], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.NewPSDriveCommand

cd : Cannot find drive. A drive with the name 'PL' does not exist.
At C:\Users\mdadmin\Desktop\ProductLockerAutomation.ps1:57 char:1
+ cd PL:
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (PL:String) [Set-Location], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

Which Folder is being used for the Shared Product Locker?:
1. ISOs
2. OVAs
Enter selection:
```

The folders it presents after the error are just local to whatever system I am running PCLI on.

**Comment by vtagion** [comment]
This is the code that is getting the datastores. It is based on a datastore having access from more than 1 host, not "all the hosts", so if you have certain datastores that are shared between 2+ hosts in your cluster, but not ALL hosts, they will show up as well.
$Datastores = Get-Datastore | where {$_.ExtensionData.Summary.MultipleHostAccess}

If you want to update this to only show DS's that are connected to ALL hosts in the cluster, I'd be happy to take the pull request.

**Comment by cajunitalian** [comment]
Understandable.  However, that does not solve my error that I am getting.

Why is PowerCLI not recognizing the Datastore for the PSDrive?

**Comment by vtagion** [comment]
Try taking this line and removing the '| Out-null' to see if/what errors are occurring.  maybe also add a "write-host $datastore" in the line before to see what the variable is actually passing.
are you using a VSAN datastore?
```
# Create new PSDrive to allow us to interact with the datastore
New-PSDrive -Location $Datastore -Name PL -PSProvider VimDatastore -Root '\' | out-null

# Change Directories to the new PSDrive
cd PL:
```
